# Generated by Django 5.0.2 on 2024-03-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carro",
            fields=[
                ("montadora", models.CharField(max_length=25)),
                ("ano", models.IntegerField()),
                ("modelo", models.CharField(max_length=20)),
                ("placa", models.CharField(max_length=10, primary_key=1, serialize=False)),
            ],
        ),
    ]
