# Generated by Django 5.0.2 on 2024-03-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_carro"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitante",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("entrada", models.IntegerField(unique=True)),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
    ]
